version: '3.8'
services:
  redis:
    image: redis:7.2.1-alpine
    container_name: banter-redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}

  django:
    image: 'python:3.12.0rc3-alpine3.18'
    container_name: banter-django
    working_dir: /api
    command: sh -c "pip freeze > requirements.txt && pip install -r requirements.txt && python manage.py runserver"
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}

