version: '3.8'
services:
  django:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - DJANGO_DEBUG=False
        #command: tail -f /dev/null
  vue:
    build:
      context: app
      dockerfile: Dockerfile.dev
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - FRONTEND_BASE=${FRONTEND_PROTOCOL}${FRONTEND_BASE}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - VITE_BACKEND_URL=http://${BACKEND_BASE}:${BACKEND_PORT}
      - VITE_BACKEND_WS_URL=ws://${BACKEND_BASE}:${BACKEND_PORT}
