version: '3.8'

services:
  redis:
    image: redis:7.2.1-alpine
    container_name: banter-redis-prod
  
  mysql:
    image: mysql:8.1.0
    container_name: banter-mysql-prod
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  django:
    build:
      context: api
      dockerfile: Dockerfile.prod
    container_name: banter-django-prod
    volumes:
      - ./api:/api/banter
    depends_on:
      - redis
      - mysql
    environment:
      - DJANGO_SECRET_KEY=mysecretkey

  vue:
    build:
      context: app
      dockerfile: Dockerfile.prod
    container_name: banter-vue-prod
    ports:
    - 80:80

  nginx:
    image: nginx:1.21-alpine
    container_name: banter-nginx-prod
    ports:
      - "8000:8000"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
      - vue

networks:
  default:
    external:
      name: mynetwork

volumes:
  dbdata: 

