version: '3.8'
services:
  django:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - DJANGO_DEBUG=True
  vue:
    build:
      context: app
      dockerfile: Dockerfile.dev
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - VITE_BACKEND_URL=${BACKEND_HOST}:${BACKEND_PORT}
