version: '3.8'
services:
  django:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
  vue:
    build:
      context: app
      dockerfile: Dockerfile.dev
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
