# Generated by Django 4.2.5 on 2023-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profilestatus_alter_profile_id_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestatus',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
