FROM node:20.7.0-alpine3.17
WORKDIR /app
COPY package*.json ./

RUN apk add --no-cache openssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout banter.key -out banter.cert \
    -subj "/C=US/ST=YourState/L=YourCity/O=YourOrganization/CN=localhost"

RUN npm install
COPY . .
CMD npm run dev -- --host

