FROM python:3.12-slim

WORKDIR /api/banter

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt /api/banter/
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . /api/banter/

CMD ["gunicorn", "banter.wsgi:application", "--bind", "0.0.0.0:8000"]

