FROM python:3.12.0rc3-alpine3.18

RUN apk add --no-cache \
    mysql-dev \
    gcc \
    musl-dev

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

WORKDIR /api/banter

CMD sh -c "python manage.py makemigrations && python manage.py migrate && uvicorn banter.asgi:application --reload --host 0.0.0.0 --port 8000"
