# Generated by Django 4.2.5 on 2023-09-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRelationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('hashed_password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilerelationstatus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_relations', to='user_profile.profile')),
                ('requester_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_relations', to='user_profile.profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilerelationstatus')),
            ],
            options={
                'ordering': ['requester_profile', 'receiver_profile'],
                'unique_together': {('requester_profile', 'receiver_profile')},
            },
        ),
    ]
