# Generated by Django 4.2.5 on 2023-09-22 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_profile.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='room.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileMessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Profile Message Statuses',
            },
        ),
        migrations.CreateModel(
            name='ProfileMessageStatusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_statuses', to='room.message')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to='user_profile.profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='room.profilemessagestatus')),
            ],
            options={
                'verbose_name': 'Profile Message Status Mapping',
                'verbose_name_plural': 'Profile Message Status Mappings',
                'unique_together': {('profile', 'message')},
            },
        ),
    ]
