# Generated by Django 4.2.5 on 2023-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
