# Generated by Django 4.2.5 on 2023-10-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_message_id_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'deleted')], default=1),
        ),
    ]
